In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
df = pd.read_csv('Housing.csv')
df.head()

price  area
0  13300000  7420
1  12250000  8960
2  12250000  9960
3  12215000  7500
4  11410000  7420

In [4]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [5]:
model.coef_

array([461.97489427])

In [6]:
model.intercept_

np.float64(2387308.4823964303)

In [7]:
model.predict([[7500]])

C:\Users\star\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([5852120.18944231])

In [8]:
import pickle

In [9]:
with open('model_pickle','wb') as f:   #write mode
    pickle.dump(model,f)

In [10]:
with open('model_pickle','rb') as f:    #read mode
    model1 = pickle.load(f)

In [11]:
model1.predict([[7500]])

C:\Users\star\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([5852120.18944231])

In [13]:
import joblib

In [14]:
 joblib.dump(model,'joblib_model')

['joblib_model']

In [15]:
obj = joblib.load('joblib_model')

In [16]:
obj.predict([[7500]])

C:\Users\star\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([5852120.18944231])